"""
Train crop models on YOLO-anchored player GT (crop_gt_yolo.json).

Architecture change vs. the original sweep:
  - GT is generated by YOLO player detection, not SIFT homography of Jay's edits
  - Full player body is guaranteed in every training crop (no leg-cutting bias)
  - angle_deg is always 0 — rawpy handles camera orientation automatically,
    so no rotation regression is needed; use_angle_head=False throughout
  - Checkpoints tagged _yolo (e.g. cropping_efficientnet_b0_yolo.pt)

At inference, run.py uses _compute_player_crop() (YOLO directly) as the primary
path; these model checkpoints are the fallback when YOLO cannot detect a player.
Because training and inference now share the same crop geometry (_PLAYER_FILL=0.60,
_HEAD_ROOM=0.22, portrait 2:3), the fallback produces consistent results.

Pre-requisite:
    python -m data.build_yolo_crop_gt

Usage:
    python sweep_crop_yolo.py                   # small + medium + large
    python sweep_crop_yolo.py --sizes small     # single backbone
"""
import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from config import CROP_GT_YOLO_FILE
from models.cropping.train import train

LOG_PATH = Path("logs/sweep_crop_yolo.jsonl")

CONFIGS = {
    "small": {
        "backbone":        "efficientnet_b0",
        "epochs":          25,
        "batch_size":      32,
        "lr":              1e-4,
        "warmup_epochs":   0,
        "grad_checkpoint": False,
        "use_angle_head":  False,
        "ckpt_tag":        "_yolo",
    },
    "medium": {
        "backbone":        "efficientnet_b3",
        "epochs":          25,
        "batch_size":      16,
        "lr":              1e-4,
        "warmup_epochs":   0,
        "grad_checkpoint": False,
        "use_angle_head":  False,
        "ckpt_tag":        "_yolo",
    },
    "large": {
        "backbone":        "vit_base_patch14_reg4_dinov2",
        "epochs":          40,
        "batch_size":      8,
        "lr":              1e-5,
        "warmup_epochs":   3,
        "grad_checkpoint": True,
        "use_angle_head":  False,
        "ckpt_tag":        "_yolo",
    },
    "resnet50": {
        "backbone":        "resnet50",
        "epochs":          25,
        "batch_size":      16,
        "lr":              1e-4,
        "warmup_epochs":   0,
        "grad_checkpoint": False,
        "use_angle_head":  False,
        "ckpt_tag":        "_yolo",
    },
}

_DEFAULT_ORDER = ["small", "medium", "large"]


def main(sizes: list[str]) -> None:
    if not CROP_GT_YOLO_FILE.exists():
        print(f"ERROR: {CROP_GT_YOLO_FILE} not found.")
        print("Run first:  python -m data.build_yolo_crop_gt")
        sys.exit(1)

    LOG_PATH.parent.mkdir(exist_ok=True)
    LOG_PATH.unlink(missing_ok=True)

    results: list[dict] = []
    for size in sizes:
        cfg = CONFIGS[size]
        print(f"\n{'='*65}")
        print(f"  {size.upper()} (box-only, YOLO GT): {cfg['backbone']}  lr={cfg['lr']:.0e}")
        print("=" * 65)
        try:
            m = train(**cfg, gt_file=CROP_GT_YOLO_FILE)
            m["size"] = size
            results.append(m)
            with open(LOG_PATH, "a") as fh:
                fh.write(json.dumps({"size": size, **m}) + "\n")
        except Exception as exc:
            print(f"  FAILED: {exc}")
            results.append({"size": size, "backbone": cfg["backbone"],
                            "mean_iou": 0.0, "median_iou": 0.0})

    _print_table(results)


def _print_table(results: list[dict]) -> None:
    if not results:
        return
    print(f"\n{'='*80}")
    print(f"  {'Size':<10} {'Backbone':<38} {'lr':>7} {'Mean IoU':>9} {'Median':>8} "
          f"{'>0.7':>6} {'>0.8':>6}")
    print("-" * 80)
    best = max(results, key=lambda x: x.get("mean_iou", 0))
    for r in sorted(results, key=lambda x: x.get("mean_iou", 0), reverse=True):
        tm  = r.get("test_metrics", r)
        m_  = tm.get("mean_iou",   r.get("mean_iou",   0))
        med = tm.get("median_iou", r.get("median_iou", 0))
        g70 = tm.get("iou_gt70",   0)
        g80 = tm.get("iou_gt80",   0)
        cfg = CONFIGS.get(r.get("size", ""), {})
        mark = "  <--" if r is best else ""
        print(f"  {r.get('size','?'):<10} {r['backbone']:<38} {cfg.get('lr',0):>7.0e} "
              f"{m_:>9.4f} {med:>8.4f} {g70:>5.1%} {g80:>5.1%}{mark}")
    print("=" * 80)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--sizes", nargs="+",
        choices=list(CONFIGS.keys()),
        default=_DEFAULT_ORDER,
    )
    args = parser.parse_args()
    main(args.sizes)
